model:
  name: "answerdotai/ModernBERT-base"
  max_length: 512
  batch_size: 4
  freeze_embeddings: true

training:
  learning_rate: 2e-5
  num_epochs: 10
  train_batch_size: 4
  eval_batch_size: 8
  weight_decay: 0.01
  warmup_steps: 500

data:
  file_path: "data/transcripts.xlsx"
  excel_sheet_name: "Sales calls"
  excel_text_col: "Transcription"
  excel_label_col: "Win /No-Win"
  train_split: 0.8
  seed: 153
  shuffle: true
  embeddings_path: "data/embeddings"
  finetune_dataset: "craig/prosus-converted"  # Sales calls dataset
  finetune_subset: "train"
